trigger:
  - main
pool:
  name: local

variables:
  buildConfiguration: 'Release'

stages:
  - stage: InstallAndBuild
    displayName: Build Frontend and Backend
    jobs:
      - job: BuildFrontend
        displayName: 'Build Frontend'
        pool:
          name: local
        steps:
          - checkout: self

          - task: NodeTool@0
            inputs:
              versionSpec: '20.x'
            displayName: 'Use Node.js 20.x'

          - script: |
              cd frontend

              echo "=== Writing .env ==="
              echo VITE_APP_NAME="WI Invoice" > .env
              echo VITE_APP_TITLE="" >> .env
              echo VITE_APP_ENV= >> .env
              echo VITE_APP_DEBUG=true >> .env
              echo VITE_APP_LOG_LEVEL=debug >> .env
              echo VITE_BASE_URL=http://localhost:3001/api >> .env

              echo "=== Showing .env ==="
              type .env

              echo "=== Checking Node and NPM ==="
              node -v
              npm -v

              echo "=== Running npm install ==="
              npm install
              if %errorlevel% neq 0 exit /b %errorlevel%

              echo "=== Running vite build ==="
              cmd /C "set NODE_ENV=production && npm run build -- --debug --logLevel info"
              if %errorlevel% neq 0 (
                echo "❌ Vite build failed"
                exit /b %errorlevel%
              )

              echo "=== Checking dist folder ==="
              if exist dist (
                dir dist
              ) else (
                echo "❌ dist folder not found"
                exit /b 1
              )
            displayName: 'Build Frontend (Windows + NODE_ENV Fix)'

          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: 'frontend/dist'
              artifactName: 'frontend-build'
              publishLocation: 'Container'

      - job: BuildBackend
        displayName: 'Build Backend'
        pool:
          name: local
        steps:
          - checkout: self  

          - task: NodeTool@0
            inputs:
              versionSpec: '20.x'
            displayName: 'Use Node.js'

          - script: |
              cd backend
              npm install
            displayName: 'Install Backend'

          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: 'backend'
              artifactName: 'backend-src'
              publishLocation: 'Container'  

  - stage: SonarQubeAnalysis
    displayName: 'Run SonarQube Code Analysis'
    jobs:
      - job: SonarQubeScan
        displayName: 'SonarQube Scanner'
        pool:
          name: local
        steps:
          - checkout: self

          - task: NodeTool@0
            inputs:
              versionSpec: '20.x'
            displayName: 'Use Node.js'

          - script: |
              echo Running Sonar Scanner...
              sonar-scanner ^
                -Dsonar.projectKey=wi-invoice ^
                -Dsonar.sources=frontend,backend ^
                -Dsonar.host.url=http://localhost:9000 ^
                -Dsonar.login=$(SONAR_TOKEN)
            displayName: 'Run SonarQube CLI Scanner'

  - stage: TestMock
    displayName: 'Mock Test Stage'
    jobs:
      - job: RunFakeTests
        displayName: 'Mock Tests'
        pool:
          name: local
        steps:
          - script: echo "Running dummy tests..."
            displayName: 'Mock Unit Test + Coverage'
