trigger:
  - main
pool:
  name: local

variables:
  buildConfiguration: 'Release'

stages:
  - stage: InstallAndBuild
    displayName: Build Frontend and Backend
    jobs:
      - job: BuildFrontend
        displayName: 'Build Frontend'
        pool:
          name: local
        steps:
          - checkout: self

          - task: NodeTool@0
            inputs:
              versionSpec: '20.x'
            displayName: 'Use Node.js 20.x'

          - script: |
              cd frontend
              echo "VITE_APP_NAME=\"WI Invoice\"" > .env
              echo "VITE_APP_TITLE=\"\"" >> .env
              echo "VITE_APP_ENV=" >> .env
              echo "VITE_APP_DEBUG=true" >> .env
              echo "VITE_APP_LOG_LEVEL=debug" >> .env
              echo "VITE_BASE_URL=http://localhost:3001/api" >> .env

              npm install
              NODE_ENV=production npm run build -- --debug --logLevel info

              echo "Build output:"
              ls -la dist || echo "❌ dist folder not found"

              if [ ! -d "dist" ]; then
                echo "❌ Build failed: dist folder not found"
                exit 1
              fi
            displayName: 'Build Frontend with Vite .env'

          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: 'frontend/dist'
              artifactName: 'frontend-build'
              publishLocation: 'Container'

      - job: BuildBackend
        displayName: 'Build Backend'
        pool:
          name: local
        steps:
          - checkout: self  

          - task: NodeTool@0
            inputs:
              versionSpec: '20.x'
            displayName: 'Use Node.js'

          - script: |
              cd backend
              npm install
            displayName: 'Install Backend'

          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: 'backend'
              artifactName: 'backend-src'
              publishLocation: 'Container'  

  - stage: SonarMock
    displayName: 'Mock SonarQube Stage'
    jobs:
      - job: SonarFake
        displayName: 'Mock Sonar'
        pool:
          name: local
        steps:
          - script: echo "Pretending to run SonarQube..."
            displayName: 'Mock SonarQube Analysis'

  - stage: TestMock
    displayName: 'Mock Test Stage'
    jobs:
      - job: RunFakeTests
        displayName: 'Mock Tests'
        pool:
          name: local
        steps:
          - script: echo "Running dummy tests..."
            displayName: 'Mock Unit Test + Coverage'
